"""
Django settings for social_media_monitoring project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jv@=$$y)8jnufwq-d4r8=_qf7sk5fkq01!^4ny5$5+&h(1saed'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    "social_media",
    'django_celery_results',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_media_monitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_media_monitoring.wsgi.application'
CORS_ALLOW_ALL_ORIGINS=True

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "SocialMediaNimar",
        "USER": "postgres",
        "PASSWORD": "ticker@1234",
        "PORT": "5432",
        'CONN_MAX_AGE': 600
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Karachi'

CELERY_RESULT_BACKEND = 'django-db'

#CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# CELERY_TIMEZONE = "America/New_York"
# TIME_ZONE = 'Asia/Karachi'
# ip:192.168.18.67:5173 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
# STATIC_ROOT=
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

from celery.schedules import crontab

# app.conf.beat_schedule = {

CELERY_BEAT_SCHEDULE = {
    'add_tracking': {
        'task': 'social_media.tasks.ad_tracking_urdu_point',  # Replace with the actual path to your first task
        'schedule': 1800,  # 900 seconds = 15 minutes
    },
    'profile_crawling_nimar': {
        'task': 'social_media.tasks.profile_based_scraping_nimar',  # Replace with the actual path to your second task
        'schedule': 3600,  # 900 seconds = 15 minutes
    },
    'web_crawling_nimar': {
        'task': 'social_media.tasks.web_scrapers_nimar',  # Replace with the actual path to your second task
        'schedule': 9600,  # 900 seconds = 15 minutes
    },
}
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Q_CLUSTER = {
#     'name': 'social_media_monitoring',
#     'workers': 4,
#     'recycle': 500,
#     'timeout': 900,
#     'compress': True,
#     'cpu_affinity': 1,
# }