# Generated by Django 4.2.8 on 2024-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_table',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads_table',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
