# Generated by Django 4.2.8 on 2024-01-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_ads_table_end_date_alter_ads_table_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_table',
            name='source',
            field=models.CharField(default='urdu_point', max_length=1000),
        ),
    ]
