# Generated by Django 4.2.8 on 2024-01-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_ads_table_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='platform_type',
            field=models.CharField(default='web', max_length=500),
        ),
    ]
